export const questionList = [
	{
		id: 1,
		question: 'Ko je stariji koka, jaje,petao ili pile?',
		answer: ['Koka', 'Jaje', 'Petao', 'Pile'],
		corectAnswer: 'Jaje',
		tezina: 'hard',
		oblast: 'Istorija',
		podoblast: 'Praistorija',
		img: '',
	},
	{
		id: 2,
		question: 'Kad je poceo ww-2?',
		answer: ['1939.', '1940', '1941', '1942'],
		corectAnswer: '1942',
		tezina: 'easy',
		oblast: 'Istorija',
		podoblast: 'Savremena istorija',
		img: '',
	},
	{
		id: 3,
		question: "Ko je naslikao' Monalizu'?",
		answer: ['Davinci', 'Mikelandjelo', 'Rembrant', 'Donatelo'],
		corectAnswer: 'Davinci',
		tezina: 'medium',
		oblast: 'Istorija umetnosti',
		podoblast: 'Slikarstvo',
		img: '',
	},
	{
		id: 4,
		question: 'Koliko ivica ima kocka?',
		answer: ['6', '8', '10', '12'],
		corectAnswer: '12',
		tezina: 'medium',
		oblast: 'Matematika',
		podoblast: 'Geometrija',
		img: '',
	},
	{
		id: 5,
		question: 'Koja je osnovna jedinica za masu?',
		answer: ['Gram', 'Kilogram', 'Tona', 'Dekagram'],
		corectAnswer: 'Kilogram',
		tezina: 'easy',
		oblast: 'Fizika',
		podoblast: 'Osnovne jedinice',
		img: '',
	},
	{
		id: 6,
		question: 'Koji je glavni grad Kanade?',
		answer: ['Toronto', 'Montreal', 'Otava', 'Oslo'],
		corectAnswer: 'Otava',
		tezina: 'easy',
		oblast: 'Geografija',
		podoblast: 'Drzave i gradovi',
		img: '',
	},
	{
		id: 7,
		question: 'Iz kog jezika vodi poreklo rec demokratija?',
		answer: ['Grckog', 'Latinskog', 'Arapskog', 'Engleskog'],
		corectAnswer: 'Grckog',
		tezina: 'easy',
		oblast: 'Jezici i knjizevnost',
		podoblast: 'Lingvistika',
		img: '',
	},
	{
		id: 8,
		question: 'Koja reka tece kroz Pariz?',
		answer: ['Loara', 'Sena', 'Temza', 'Pariso'],
		corectAnswer: 'Sena',
		tezina: 'hard',
		oblast: 'Geografija',
		podoblast: 'Reke i mora',
		img: '',
	},
];
